### add category
POST http://localhost:8080/api/v1.0/categories
Content-Type: application/json

{
  "name": "Ear phones",
  "description": "all kinds of ear phones available",
  "bgColor": "#ffffff"
}

### read categories
GET http://localhost:8080/api/v1.0/categories
Content-Type: application/json

### delete category
DELETE http://localhost:8080/api/v1.0/categories/7be165b6-4d72-43d4-9dc5-7ac85040aaaf
Content-Type: application/json

### add category with file
POST http://localhost:8080/api/v1.0/categories
Content-Type: multipart/form-data; boundary=boundary123

--boundary123
Content-Disposition: form-data; name="category"
Content-Type: application/json

{
  "name": "Keyboards",
  "description": "all kinds of keyboards available",
  "bgColor": "#ffffff"
}
--boundary123
Content-Disposition: form-data; name="file"; filename="keyboard.png"
Content-Type: image/png

< imgs/keyboard.png
--boundary123--