### add category
POST http://localhost:8080/api/v1.0/categories
Content-Type: application/json

{
  "name": "Ear phones",
  "description": "all kinds of ear phones available",
  "bgColor": "#ffffff"
}

### read categories
GET http://localhost:8080/api/v1.0/categories
Content-Type: application/json

### delete category
DELETE http://localhost:8080/api/v1.0/admin/categories/7be165b6-4d72-43d4-9dc5-7ac85040aaaf
Content-Type: application/json

### add category with file
POST http://localhost:8080/api/v1.0/admin/categories
Content-Type: multipart/form-data; boundary=boundary123

--boundary123
Content-Disposition: form-data; name="category"
Content-Type: application/json

{
  "name": "Mouses",
  "description": "all kinds of mouses available",
  "bgColor": "#FF6B81"
}
--boundary123
Content-Disposition: form-data; name="file"; filename="mouse.png"
Content-Type: image/png

< imgs/mouse.png
--boundary123--

### encode password
POST http://localhost:8080/api/v1.0/encode
Content-Type: application/json

{
  "password": "123456"
}

### create user
POST http://localhost:8080/api/v1.0/admin/register
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJidXNoYW5AZXhhbXBsZS5jb20iLCJpYXQiOjE3Njc3MDg2NzUsImV4cCI6MTc2Nzc0NDY3NX0.g_uy5CAX9lOjf6oAte3MtXy89oEy1b02ZQcoxEIAlRg
Content-Type: application/json


{
  "name": "Lisa",
  "email": "lisa@example.com",
  "password": "12345",
  "role": "ROLE_USER"
}

### login in admin
POST http://localhost:8080/api/v1.0/login
Content-Type: application/json

{
  "email": "bushan@example.com",
  "password": "123456"
}

### login in normal user
POST http://localhost:8080/api/v1.0/login
Content-Type: application/json

{
  "email": "nico@example.com",
  "password": "123456"
}

### delete user
DELETE http://localhost:8080/api/v1.0/admin/users/52b8ecc2-708d-45de-bb5c-222dfed4b44f
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJidXNoYW5AZXhhbXBsZS5jb20iLCJpYXQiOjE3Njc3MDg2NzUsImV4cCI6MTc2Nzc0NDY3NX0.g_uy5CAX9lOjf6oAte3MtXy89oEy1b02ZQcoxEIAlRg
Content-Type: application/json


### read users
GET http://localhost:8080/api/v1.0/admin/users
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJidXNoYW5AZXhhbXBsZS5jb20iLCJpYXQiOjE3Njc3OTQ4ODYsImV4cCI6MTc2NzgzMDg4Nn0.PhrN3o6WwTJLntF7NZJ5bJO1X-Zfe2M4snkTR6TBR-A

### add item with file
POST http://localhost:8080/api/v1.0/admin/items
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJidXNoYW5AZXhhbXBsZS5jb20iLCJpYXQiOjE3Njc3MzAyOTUsImV4cCI6MTc2Nzc2NjI5NX0.2uFmEH-Kozub2VBDopN6OS1H-LxYwoH2f-wg-EoS82s
Content-Type: multipart/form-data; boundary=boundary123

--boundary123
Content-Disposition: form-data; name="item"
Content-Type: application/json

{
  "name": "HP basic Mouse",
  "description": "basic Mouse from HP",
  "price": 250.00,
  "categoryId": "ba1f9d37-5271-4838-9541-4e3ed9c78cae"
}
--boundary123
Content-Disposition: form-data; name="file"; filename="mouse.png"
Content-Type: image/png

< imgs/mouse.png
--boundary123--

### read items
GET http://localhost:8080/api/v1.0/items
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJidXNoYW5AZXhhbXBsZS5jb20iLCJpYXQiOjE3Njc3MzAyOTUsImV4cCI6MTc2Nzc2NjI5NX0.2uFmEH-Kozub2VBDopN6OS1H-LxYwoH2f-wg-EoS82s
Content-Type: application/json

### delete items
DELETE http://localhost:8080/api/v1.0/admin/items/42b3b520-d09f-4b7f-b313-a4c364a77aac
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJidXNoYW5AZXhhbXBsZS5jb20iLCJpYXQiOjE3Njc3MzAyOTUsImV4cCI6MTc2Nzc2NjI5NX0.2uFmEH-Kozub2VBDopN6OS1H-LxYwoH2f-wg-EoS82s
Content-Type: application/json

### create order
POST http://localhost:8080/api/v1.0/orders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJidXNoYW5AZXhhbXBsZS5jb20iLCJpYXQiOjE3NjgxMzg0OTAsImV4cCI6MTc2ODE3NDQ5MH0.Ll0A_vVnpCBOIXzczheXHj4_GegdvIeq0RvxT9qKXYI

{
    "customerName": "Lorry",
    "phoneNumber": "123-2444-099",
    "cartItems": [
      {
        "itemId": "230876rr",
        "name": "HP headphones",
        "price": 250.00,
        "quantity": 1
      }
    ],
    "subtotal":  500.00,
    "tax": 0.01,
    "grandTotal": 550.00,
    "paymentMethod": "CASH"
}

### delete order
DELETE http://localhost:8080/api/v1.0/orders/ORD1768139413627
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJidXNoYW5AZXhhbXBsZS5jb20iLCJpYXQiOjE3NzA0NjcwMTUsImV4cCI6MTc3MDUwMzAxNX0.3SKvb3A64Y_bflJw17PaknQ5bQPqUIM-o7N8rFC0nI4
Content-Type: application/json

### read orders
GET http://localhost:8080/api/v1.0/orders/latest
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJidXNoYW5AZXhhbXBsZS5jb20iLCJpYXQiOjE3NjgwMzYwMDEsImV4cCI6MTc2ODA3MjAwMX0.3hU8THjLOiZ4QtQ_Eoxnu8_k712__BjK0LiYgRpPhWM
Content-Type: application/json

### create stripe payment order
POST http://localhost:8080/api/v1.0/payments/payment-intent
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJidXNoYW5AZXhhbXBsZS5jb20iLCJpYXQiOjE3NjgxMzg0OTAsImV4cCI6MTc2ODE3NDQ5MH0.Ll0A_vVnpCBOIXzczheXHj4_GegdvIeq0RvxT9qKXYI

{
  "amount": 50.00,
  "currency": "eur"
}


### read dashboard data
GET http://localhost:8080/api/v1.0/dashboard
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJidXNoYW5AZXhhbXBsZS5jb20iLCJpYXQiOjE3Njg0ODYwNjQsImV4cCI6MTc2ODUyMjA2NH0.Cswd5_ZtcQfO65ffHewYqS7eLRYCUQDn_0E-SSkpLrM
Content-Type: application/json



### get one order
GET http://localhost:8080/api/v1.0/orders/ORD1770544473912
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJidXNoYW5AZXhhbXBsZS5jb20iLCJpYXQiOjE3NzA1NDY4MjMsImV4cCI6MTc3MDU4MjgyM30.VnhrgQva9ymgtLeJb-jLJE3JpUHydnikeM4mcxOfVF0
